version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # JavaScript dependencies in client directory
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
