FROM postgres:15

RUN apt-get update && \
  apt-get install -y --no-install-recommends postgresql-contrib

ENV POSTGRES_DB=railway
ENV POSTGRES_USER=bpon_admin
ENV POSTGRES_PASSWORD=bpon_pass

# Copy in the load-extensions script
COPY bin/load-extensions.sh /docker-entrypoint-initdb.d/load-extensions.sh
RUN chmod 0755 /docker-entrypoint-initdb.d/load-extensions.sh
