version: "3.4"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-pg-dev
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis-dev
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
