# Build plan from the provider
[phases.setup]
nixPkgs = ['nodejs_16', 'binutils', 'gcc', 'curl', 'rust-bin.stable.latest.default']

[phases.build]
cmds = ['cd client/ && npm i && NODE_OPTIONS=--openssl-legacy-provider npm run build', './touch_env.sh', 'mkdir -p bin', 'cargo build --release', 'cp target/release/bpon bin']
