# Build plan from the provider
[phases.setup]
nixPkgs = ['nodejs_16', 'binutils', 'gcc', 'curl', 'bash', 'rust-bin.stable.latest.default']

[phases.install]
cmds = ['./touch_env.sh', 'cd client/ && npm i']

[phases.build]
dependsOn = ['install']
cmds = ['cd client/ && NODE_OPTIONS=--openssl-legacy-provider npm run build', 'mkdir -p bin', 'cargo build --release', 'cp target/release/bpon bin']
