ALTER TABLE "tracking_codes"
    DROP COLUMN "created_at",
    DROP COLUMN "updated_at",
    ADD COLUMN "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN "updated_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL;
